version: "3"

services:
  nafurf-db:
    container_name: nafurf-db
    image: "postgres:latest"
    ports:
      - 5436:5432
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=nafurf
      - POSTGRES_PASSWORD=nafurf
      - POSTGRES_DATABASE=nafurf
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
  db-data-test:
      driver: local