-- CreateTable
CREATE TABLE "User" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "ign" STRING,
    "lolId" STRING,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Game" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "matchId" STRING NOT NULL,
    "gameMode" STRING,
    "isMatchLoaded" BOOL NOT NULL DEFAULT false,
    "periodId" INT4,
    "duration" FLOAT8,
    "gameCreation" TIMESTAMP(3),
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Game_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PlayerStat" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "gameId" INT4 NOT NULL,
    "championId" INT4 NOT NULL,
    "userId" INT4,
    "sumName" STRING NOT NULL,
    "puuid" STRING NOT NULL,
    "isAllyTeam" BOOL NOT NULL,
    "kills" INT4 NOT NULL,
    "deaths" INT4 NOT NULL,
    "assists" INT4 NOT NULL,
    "damage" INT4 NOT NULL,
    "tanked" INT4 NOT NULL,
    "mitigated" INT4 NOT NULL,
    "totalTimeCCDealt" INT4 NOT NULL,
    "isFirstBloodKill" BOOL NOT NULL,
    "doubleKills" INT4 NOT NULL,
    "tripleKills" INT4 NOT NULL,
    "quadraKills" INT4 NOT NULL,
    "pentaKills" INT4 NOT NULL,
    "timeCCingOthers" INT4 NOT NULL,
    "goldEarned" INT4 NOT NULL,
    "totalMinionsKilled" INT4 NOT NULL,
    "neutralMinionsKilled" INT4 NOT NULL,
    "isWin" BOOL NOT NULL,
    "totalTimeSpentDead" INT4 NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "totalCs" INT4 NOT NULL,

    CONSTRAINT "PlayerStat_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SumSpells" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "sumId" INT4 NOT NULL,
    "name" STRING,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SumSpells_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Item" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "itemId" INT4 NOT NULL,
    "name" STRING,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Item_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Stat" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" INT4 NOT NULL,
    "championStatId" INT4 NOT NULL,
    "periodId" INT4 NOT NULL,
    "playerStatId" INT4 NOT NULL,
    "kills" INT4 NOT NULL,
    "deaths" INT4 NOT NULL,
    "assists" INT4 NOT NULL,
    "damage" INT4 NOT NULL,
    "reduction" INT4 NOT NULL,
    "kda" INT4 NOT NULL,
    "perf" INT4 NOT NULL,
    "xClass" INT4 NOT NULL,
    "comment" STRING,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Stat_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Champion" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "support" BOOL NOT NULL DEFAULT false,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Champion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ChampionStat" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "periodId" INT4 NOT NULL,
    "winrate" FLOAT8 NOT NULL,
    "championId" INT4 NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ChampionStat_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Period" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Period_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LolRequest" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "count" INT4 NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LolRequest_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_PlayerStatToSumSpells" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateTable
CREATE TABLE "_ItemToPlayerStat" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "User_name_key" ON "User"("name");

-- CreateIndex
CREATE UNIQUE INDEX "User_ign_key" ON "User"("ign");

-- CreateIndex
CREATE UNIQUE INDEX "User_lolId_key" ON "User"("lolId");

-- CreateIndex
CREATE UNIQUE INDEX "Game_matchId_key" ON "Game"("matchId");

-- CreateIndex
CREATE UNIQUE INDEX "SumSpells_sumId_key" ON "SumSpells"("sumId");

-- CreateIndex
CREATE UNIQUE INDEX "SumSpells_name_key" ON "SumSpells"("name");

-- CreateIndex
CREATE UNIQUE INDEX "Item_itemId_key" ON "Item"("itemId");

-- CreateIndex
CREATE UNIQUE INDEX "Item_name_key" ON "Item"("name");

-- CreateIndex
CREATE UNIQUE INDEX "Stat_playerStatId_key" ON "Stat"("playerStatId");

-- CreateIndex
CREATE UNIQUE INDEX "Champion_name_key" ON "Champion"("name");

-- CreateIndex
CREATE UNIQUE INDEX "ChampionStat_championId_periodId_key" ON "ChampionStat"("championId", "periodId");

-- CreateIndex
CREATE UNIQUE INDEX "_PlayerStatToSumSpells_AB_unique" ON "_PlayerStatToSumSpells"("A", "B");

-- CreateIndex
CREATE INDEX "_PlayerStatToSumSpells_B_index" ON "_PlayerStatToSumSpells"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_ItemToPlayerStat_AB_unique" ON "_ItemToPlayerStat"("A", "B");

-- CreateIndex
CREATE INDEX "_ItemToPlayerStat_B_index" ON "_ItemToPlayerStat"("B");

-- AddForeignKey
ALTER TABLE "Game" ADD CONSTRAINT "Game_periodId_fkey" FOREIGN KEY ("periodId") REFERENCES "Period"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PlayerStat" ADD CONSTRAINT "PlayerStat_championId_fkey" FOREIGN KEY ("championId") REFERENCES "Champion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PlayerStat" ADD CONSTRAINT "PlayerStat_gameId_fkey" FOREIGN KEY ("gameId") REFERENCES "Game"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PlayerStat" ADD CONSTRAINT "PlayerStat_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Stat" ADD CONSTRAINT "Stat_championStatId_fkey" FOREIGN KEY ("championStatId") REFERENCES "ChampionStat"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Stat" ADD CONSTRAINT "Stat_periodId_fkey" FOREIGN KEY ("periodId") REFERENCES "Period"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Stat" ADD CONSTRAINT "Stat_playerStatId_fkey" FOREIGN KEY ("playerStatId") REFERENCES "PlayerStat"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Stat" ADD CONSTRAINT "Stat_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChampionStat" ADD CONSTRAINT "ChampionStat_championId_fkey" FOREIGN KEY ("championId") REFERENCES "Champion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChampionStat" ADD CONSTRAINT "ChampionStat_periodId_fkey" FOREIGN KEY ("periodId") REFERENCES "Period"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_PlayerStatToSumSpells" ADD CONSTRAINT "_PlayerStatToSumSpells_A_fkey" FOREIGN KEY ("A") REFERENCES "PlayerStat"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_PlayerStatToSumSpells" ADD CONSTRAINT "_PlayerStatToSumSpells_B_fkey" FOREIGN KEY ("B") REFERENCES "SumSpells"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ItemToPlayerStat" ADD CONSTRAINT "_ItemToPlayerStat_A_fkey" FOREIGN KEY ("A") REFERENCES "Item"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ItemToPlayerStat" ADD CONSTRAINT "_ItemToPlayerStat_B_fkey" FOREIGN KEY ("B") REFERENCES "PlayerStat"("id") ON DELETE CASCADE ON UPDATE CASCADE;

